// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAXEK0VPMNVSq0PsNa7y7rXrTVHHpX2Qo',
    appId: '1:1094537355938:android:c3a5420e64bbdf1c3a2dfb',
    messagingSenderId: '1094537355938',
    projectId: 'cadeli-18b35',
    storageBucket: 'cadeli-18b35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgtPJcl3A9880PS4LYijGEItoR669KUOg',
    appId: '1:1094537355938:ios:916e78ff185508983a2dfb',
    messagingSenderId: '1094537355938',
    projectId: 'cadeli-18b35',
    storageBucket: 'cadeli-18b35.firebasestorage.app',
    androidClientId: '1094537355938-3rrp6ps9ah0fpbu5itju44ccvbh5slqn.apps.googleusercontent.com',
    iosClientId: '1094537355938-9trii6dnepvq6o7uhh86a4e4vbte2hvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cadeli',
  );
}
